---
titile: "函数"
tags: go
---

函数包含若干连续执行的语句，可以在代码中通过函数调用执行这些语句。函数是多数编程语言的重要特性之一。

## 函数

在Go中，函数声明的格式为：

```go
func name(parameterList) (resultList) {
    body
}
```

- 形参列表指定的一组变量的参数名和参数类型，这些变量由调用者通过函数调用传入。在Go中，实参按值传递，所以修改形参不会对外部的实参产生影响，除非提供的形参包括引用类型（如Slice, `map`, 函数变量等）。
- 返回列表指定了函数返回值的类型。函数可以返回一个或多个返回值，也可以没有返回值。当函数返回一个未命名变量或者没有返回值时，返回列表的括号可以省略。

```go
func hypot(x, y float64) float64 {
    return math.Sqrt(x*x + y*y)
}
```

返回列表中的每个命名变量在进入函数时都会被初始化为对应的零值。如果返回列表中有命名变量，那么在`return`时可以省略后面的操作数，称为 **裸返回**。裸返回会将返回列表中的每个变量按照顺序返回，返回列表中各个变量的值等于`return`前各个变量的值。

```go
func add(x, y int) (z int) {
    z = x + y
    return
}
```

Go中允许递归，即函数调用自身。许多其他编程语言使用固定长度的函数调用栈，大小从64KB到2MB不等，在这些语言中函数递归层数过深会导致爆栈溢出。Go语言使用可变长度的栈，栈的大小可随着递归层数的增加而增加，最多可达到1GB，这使得我们在大多数情况下可以安全使用递归而无须担心栈溢出问题。

## 错误处理

许多编程语言使用异常机制处理错误，如C++中的`try`/`catch`，Python中的`try`/`except`等。Go中没有使用异常机制，而是使用常规的控制流(`if`, `return`等)来处理函数错误。在Go中，如果函数调用发生错误，通常会把错误作为函数的最后一个返回值返回。

如果错误只有一种类型，则通常使用`bool`来标识错误。

```go
value, ok := cache.Lookup(key)
if !ok {
    fmt.Println("error: %s does not exist", key)
}
```

如果错误由多种类型，则使用`error`类型来表示错误

```go
resp, err := http.Get(url)
if err != nil {
    return nil, err
}
```

### 错误处理策略

在Go中，有五种常见的错误处理策略：

1. 向上传递错误：在被调函数中发生错误时将错误返回主调函数

```go
resp, err := http.Get(url)
if err != nil {
    return nil, err
}
```

2. 对出错的操作重试

```go
const timeout = 1 * time.Minute
deadline = time.Now().Add(timeout)
for tries := 0; time.Now().Before(deadline); tries++ {
    _, err := http.Head(url)
    if err == nil {
        return nil // success
    }
    time.Sleep(time.Second << uint(tries)) // wait
}
```

3. 终止程序（这种处理通常发生在主程序中）

```go
if err := WaitForServer(url); err != nil {
    fmt.Fprintf(Os.Stderr, "Site is down: %v\n", err)
    os.Exit(1)
}
```

4. 只记录错误信息，然后程序继续运行

```go
if err := Ping(); err != nil {
    log.Printf("ping failed: %v;\n", err)
}
```

5. 在极少数情况下，我们我们可以直接忽略错误，但是最好在一旁用注释表明忽略的意图。

```go
dir, err := ioutil.TempDir("", "scratch")
if err := nil {
    return fmt.Errorf("failed to create temp dir: %v", err)
}

os.RemoveAll(dir) // ignore errors; $TMPDIR is cleaned periodically
```

### `panic`和`recover`

Go中提供了两个内置函数`panic`和`recover`用来处理Go运行时的错误。
- `panic`：主动抛出一个错误
- `recover`：捕获panic抛出的错误并返回。

Go中的错误一般通过函数返回值传递；`panic`通常处理严重的错误或者预料之外的错误。如regexp模块中的`Compile`编译一个正则表达式，如果正则表达式语法错误编译失败，则将错误通过返回值返回。但是调用者在调用函数时通常可以确保函数调用不会失败，因此`MustCompile`对`Compile`进行了包装，在发生错误时直接`panic`宕机来简化错误处理逻辑。

```go
func MustCompile(str string) *Regexp {
    regexp, err := Compile(str)
    if err != nil {
        panic(`regexp: Compile(` + quote(str) + `): ` + err.Error())
    }
    return regexp
}
```

`recover`可以捕获`panic`抛出的错误并返回。由于大多数Go内部错误都是不可恢复的，因此应该谨慎使用`recover`：对于少数可以恢复的错误类型，定义一个明确的非导出类型并抛出（如下例中的`bailout{}`）；在进行恢复时对抛出的错误进行检查，如果错误类型是前文指定的可恢复情形，那么就执行恢复动作，否则继续`panic`抛出错误。

```go
defer func() {
        switch p := recover(); p {
        case nil: // no panic
        case bailout{}:
            fmt.Println("recovering: multiple elements")
        default:
            panic(p)
        }
}()
```

## 函数变量

函数变量可以存储函数，通过函数变量可以调用其存储的函数。具有不同签名的函数具有不同的类型。

```go
func square(n int) int { 
    return n * n
}

func product(m, n int) int { 
    return m * n
}

var f func(int) int
f = square
fmt.Println(f(3))

f = product // error! cannot assign func(int, int) int to f(int) int
```

函数变量的零值为`nil`。空的函数变量不能调用。

```go
var f func(int) int
a := f(3) // error!
```

函数变量可以和`nil`进行比较，但是不同函数变量之间是不可比较的。

## 匿名函数

Go中允许声明函数字面量，即没有名称的函数，也被称为**匿名函数**。 匿名函数的声明类似于常规函数的声明，但是没有函数的名称。

```go
converted := strings.Map(func(r rune) rune { return r + 1 }, "HAL-9000")
```

Go中通过定义匿名函数可以实现闭包：在函数内部定义匿名函数，内部函数可以使用外部函数的变量。

```go
func squares() func() int {
    var x int
    return func() int {
        // closure here, x is stored outside. ref x
        x++
        return x * x
    }
}

f := squares()
fmt.Println(f())
fmt.Println(f())
fmt.Println(f())
```

## 变长函数

某些函数支持可变的参数个数，如`fmt.Printf`。定义变长函数的方法是在最后一个参数的类型前添加`...`，表示此处可以传入任意数目的该类型参数。

```go
func sum(vals ...int) int {
    total := 0
    for _, val := range vals {
        total += val
    }
    return total
}

integers := []int{2, 4, 6, 8}
fmt.Println(sum(1, 2, 3, 4))
fmt.Println(sum(integers...))
```

在函数内部，变长参数表示为一个指定类型的slice. 如果要传入的参数已经被打包在了一个slice中，在调用变长函数时可以通过在slice后添加`...`来正确传递变长参数。

## defer

defer语句就是在普通的函数或方法调用前添加`defer`关键字。defer语句会在语句执行时求值，但是在函数结束后才调用。defer语句通常用于成对的操作，如打开/关闭资源，连接/断开，加锁/解锁等。使用defer语句确保在控制流复杂的情况下资源也能保证被关闭。

```go
func title(url string) error {
    resp, err := http.Get(url)
    if err != nil {
        return err
    }
    defer resp.Body.Close()

    ct := resp.Header.Get("Content-Type")
    if ct != "text/html" && !strings.HasPrefix(ct, "text/html") {
        return fmt.Errorf("%s has type %s, not text/html", url, ct)
    }

    doc, err := html.Parse(resp.Body)
    if err != nil {
        return err
    }

    if title, ok := findTitle(doc); !ok {
        fmt.Println("No title found")
    } else {
        fmt.Printf("title: %s\n", title)
    }
    return nil
}
```

`defer`也可以用来调试复杂的函数，即在函数的入口和出口处设置调试行为。如下所示，在对`trace`函数进行求值时执行入口处的调试动作；在被测函数退出后，闭包内定义的出口处的调试动作会被执行。

```go
func BigSlowOperation() {
    defer trace("BigSlowOperation")()
    time.Sleep(10 * time.Second)
}

func trace(name string) func() {
    start := time.Now()
    log.Printf("enter %s", name)
    return func() {
        log.Printf("exit %s (%s)", name, time.Since(start))
    }
}
```